#pragma once

#define SHADERS_FOLDER_NAME "Shaders"
#define MODELS_FOLDER_NAME "Models"
#define TEXTURES_FOLDER_NAME "Textures"
#define SCENE_FOLDER_NAME "Scenes"
#define CONFIGURATION_FOLDER_NAME "Config"
#define DATA_FOLDER_NAME "Data"

#define DATA_PATH "../" DATA_FOLDER_NAME
#define SHADERS_PATH DATA_PATH "/" SHADERS_FOLDER_NAME
#define MODELS_PATH DATA_PATH "/" MODELS_FOLDER_NAME
#define TEXTURES_PATH DATA_PATH "/" TEXTURES_FOLDER_NAME
#define CONFIGURATION_PATH DATA_PATH "/" CONFIGURATION_FOLDER_NAME
#define SCENE_PATH DATA_PATH "/" SCENE_FOLDER_NAME